language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:ubuntu-cloud-archive/mitaka-staging'
    packages:
    - gcc-4.8
    - g++-4.8
    - libvirt-dev

env:
  - CXX=g++-4.8

script:
  - make test
