language: node_js

env:
  - CXX=g++-4.8

node_js:
  - '0.12'
  - '4'

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get -q update
  - sudo apt-get -y install libvirt-dev

script:
  - make test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
