language: node_js
node_js:
  - '4'
  - '6'

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:ubuntu-cloud-archive/mitaka-staging'
    packages:
    - gcc-4.8
    - g++-4.8
    - libvirt-dev
    - libvirt-bin
    - qemu

env:
  - CXX=g++-4.8

before_script:
  - sudo sh -c "sed -i 's/^\(unix_sock_rw_perms\s*=\).*$/\1 \"0777\"/' /etc/libvirt/libvirtd.conf"
  - sudo service libvirt-bin restart

script:
  - make test
